apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: am4ex6uzy-java-springboot
  janus-idp.io/tekton: am4ex6uzy-java-springboot
  backstage.io/kubernetes-id: am4ex6uzy-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: am4ex6uzy-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
